#!/usr/bin/env bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --travis pulp_rpm_prerequisites' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template
#
# NOTE: Deleted lines to remove unnecessary/broken work for prereq roles
#       Aslo ran the "Travis to GH actions" sed commands

set -mveuo pipefail

export PRE_BEFORE_INSTALL=$GITHUB_WORKSPACE/.github/pre_before_install.sh
export POST_BEFORE_INSTALL=$GITHUB_WORKSPACE/.github/post_before_install.sh

COMMIT_MSG=$(git log --format=%B --no-merges -1)
export COMMIT_MSG

if [ -f $PRE_BEFORE_INSTALL ]; then
    $PRE_BEFORE_INSTALL
fi

if [[ -n $(echo -e $COMMIT_MSG | grep -P "Required PR:.*" | grep -v "https") ]]; then
  echo "Invalid Required PR link detected in commit message. Please use the full https url."
  exit 1
fi

if [ "$GITHUB_EVENT_NAME" = "pull_request" ] || [ -z "${GITHUB_REF##*/}" -a "${GITHUB_REF##*/}" != "master" ]
then
  export PULP_PR_NUMBER=$(echo $COMMIT_MSG | grep -oP 'Required\ PR:\ https\:\/\/github\.com\/pulp\/pulpcore\/pull\/(\d+)' | awk -F'/' '{print $7}')
  export PULP_SMASH_PR_NUMBER=$(echo $COMMIT_MSG | grep -oP 'Required\ PR:\ https\:\/\/github\.com\/pulp\/pulp-smash\/pull\/(\d+)' | awk -F'/' '{print $7}')
  export PULP_ROLES_PR_NUMBER=$(echo $COMMIT_MSG | grep -oP 'Required\ PR:\ https\:\/\/github\.com\/pulp\/pulp_installer\/pull\/(\d+)' | awk -F'/' '{print $7}')
  export PULP_BINDINGS_PR_NUMBER=$(echo $COMMIT_MSG | grep -oP 'Required\ PR:\ https\:\/\/github\.com\/pulp\/pulp-openapi-generator\/pull\/(\d+)' | awk -F'/' '{print $7}')
  export PULP_OPERATOR_PR_NUMBER=$(echo $COMMIT_MSG | grep -oP 'Required\ PR:\ https\:\/\/github\.com\/pulp\/pulp-operator\/pull\/(\d+)' | awk -F'/' '{print $7}')
else
  export PULP_PR_NUMBER=
  export PULP_SMASH_PR_NUMBER=
  export PULP_ROLES_PR_NUMBER=
  export PULP_BINDINGS_PR_NUMBER=
  export PULP_OPERATOR_PR_NUMBER=
fi

cd ..
git clone --depth=1 https://github.com/pulp/pulp_installer.git
if [ -n "$PULP_ROLES_PR_NUMBER" ]; then
  cd pulp_installer
  git fetch --depth=1 origin pull/$PULP_ROLES_PR_NUMBER/head:$PULP_ROLES_PR_NUMBER
  git checkout $PULP_ROLES_PR_NUMBER
  cd ..
fi
cd pulp_rpm_prerequisites

if [ -f $POST_BEFORE_INSTALL ]; then
    $POST_BEFORE_INSTALL
fi
